version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: m2c_digital_rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: m2c_digital
      RABBITMQ_DEFAULT_PASS: m2c_digital

  postgres:
    image: postgres:15
    container_name: m2c_digital_postgres
    restart: always
    environment:
      POSTGRES_USER: m2c_digital
      POSTGRES_PASSWORD: m2c_digital
      POSTGRES_DB: m2c_digital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: